### ISSUE TITLE
Make GPIO high

### ISSUE THREAD

**Issue by eliabieri** [eadf/esp8266_easygpio#1]
maybe I`m dumb but how can I set a gpio high?
I use this to specify which gpio pin i want and that the pin should be an output:

uint8_t gpio_pin = 0;
EasyGPIO_PinMode pinMode = EASYGPIO_OUTPUT;

But how can i set the level of the gpio to high or low now?

**Comment by eadf** [comment]
There are simple access macros in the "standard" gpio.h
GPIO_OUTPUT_SET(gpio_no, bit_value) // GPIO_OUTPUT_SET(0,1) sets gpio0 to high
GPIO_DIS_OUTPUT(gpio_no) // GPIO_DIS_OUTPUT(2) turns off output on gpio2
GPIO_INPUT_GET(gpio_no) // GPIO_INPUT_GET(12) returns the input value of gpio12

I could have created new macros but i prefer to use an accepted API instead of creating something new that does the same thing. (At least if the standard API is reasonably easy to use)

But maybe i should mention gpio.h in the examples, thanks for the feedback

**Comment by eliabieri** [comment]
Thanks for your help.
Would it be hard to implement the arduino style GPIO modification.
Something like:
pinMode(3,OUTPUT);
digitalWrite(3,HIGH);

## 

Elia Bieri
whateveryouwant@eliabieri.com

**Comment by eadf** [comment]
No, it would be trivial. 
I could for example make a macro digitalWrite() that points back to GPIO_OUTPUT_SET(). 
But would that really solve anything? I created the this library because i found the pin_id, pin_name, and pin_func mess overly complicated and hard do deal with in a generic way.
But a problem that a simple find-and-replace in a text editor can solve? 
I dunno - I have to think about that a bit.

I've seen projects for esp8266 that try to mimic the arduino language in every way (minus the c++, that is), and that's not my goal.

Never the less, i appreciate your input

**Comment by eliabieri** [comment]
Ok it works now the way you told me.
Thank you for the time you invested!
